In [1]:
#escrevendo o primeiro programa
print("Seja Bem Vindo!!!")

Seja Bem Vindo!!!


In [2]:
print("Hello\nWorld!")

Hello
World!


<h1>Tipos</h1>

In [6]:
a = 2
print(float(a))

2.0


In [8]:
a = 5.55
print(int(a))

5


In [9]:
a = '55'
print(int(a))

55


In [11]:
a = 2015
print(str(a))

2015


In [12]:
a = 1
print(bool(a))

True


<h1>Trabalhando String</h1>

In [14]:
a = "Vida Louca"

In [15]:
a[0]

'V'

In [16]:
a[-1]

'a'

In [31]:
a[0:4]

'Vida'

In [32]:
"0123456".find('1')

1

In [33]:
name = 'Lizz'
print(name[0:2])

Li


In [34]:
var = '01234567'
print(var[::2])

0246


<h1>Tuplas</h1>

In [38]:
colecao = ("Livros", 10, 6.5, ['amanda', 'café', 4, 5.9], (4, 5, 6))
print(colecao)

('Livros', 10, 6.5, ['amanda', 'café', 4, 5.9], (4, 5, 6))


In [39]:
colecao[0]

'Livros'

In [40]:
colecao[3]

['amanda', 'café', 4, 5.9]

In [41]:
colecao[3][3]

5.9

In [55]:
a = "Café, 11.00"
b = a.split(',')


In [56]:
print(a)

Café, 11.00


In [57]:
print(b)

['Café', ' 11.00']


In [60]:
A=(0,1,2,3)
A[-1]

3

In [61]:
B=["a","b","c"]
B[1:]

['b', 'c']

In [62]:
a = {"a", 'Maria', 'pedro'}
'pedro' in a

True

In [63]:
S={'A','B','C'}

U={'A','Z','C'}

U.union(S)

{'A', 'B', 'C', 'Z'}

In [64]:
S={'A','B','C'}

U={'A','Z','C'}

S & U

{'A', 'C'}

In [65]:
D={'a':0,'b':1,'c':2}
D.values()

dict_values([0, 1, 2])

In [68]:
a=1

def add(b):

    return a+b

c=add(10)
c

11

In [71]:
def f(*x):

    return sum(c)


In [72]:
example1 = "ambientesa.txt"
file1 = open(example1, "r")

In [73]:
file1.name

'ambientesa.txt'

In [74]:
file1.mode

'r'

In [75]:
FileContent = file1.read()
FileContent

'https://prehom.dpf.gov.br/siscaer\n\nhttps://prehom.dpf.gov.br/siscaer-internet\n\nhttps://prehom.dpf.gov.br/siscaer-publico-web/#/\n\nmob2\n\nHierarquia São Paulo:\n\n\nCadastrar com: heron.hwpb (Usuário comum)\n\nAprovar pela AD com: estevao.egl (Autoridade Determinante)\n\nAprovar pela AS com: rosseti.dr (Autoridade Superior)\n\nAprovar pelo DG com: galloro.ravg (Diretor Geral)\n\nNEIVA MARQUES SOCHETE VIVAN neiva.nmsv\nrodrigo souza de oliveira rodrigo souza.rso\n\nUsuário Semob: souza.rso (Esse usuário equivale ao perfil ADM, visualiza mais menus e tem permissão para consultar qualquer ordem).\n\nLinks para acesso ao sistema:\n\nPreHom: https://prehom.dpf.gov.br/mobilizacao2/inicio\n\nHomologação: https://sistemashom.dpf.gov.br/mobilizacao2/missao-policial/consultar\n\n\n\n'

In [76]:
print(FileContent)

https://prehom.dpf.gov.br/siscaer

https://prehom.dpf.gov.br/siscaer-internet

https://prehom.dpf.gov.br/siscaer-publico-web/#/

mob2

Hierarquia São Paulo:


Cadastrar com: heron.hwpb (Usuário comum)

Aprovar pela AD com: estevao.egl (Autoridade Determinante)

Aprovar pela AS com: rosseti.dr (Autoridade Superior)

Aprovar pelo DG com: galloro.ravg (Diretor Geral)

NEIVA MARQUES SOCHETE VIVAN neiva.nmsv
rodrigo souza de oliveira rodrigo souza.rso

Usuário Semob: souza.rso (Esse usuário equivale ao perfil ADM, visualiza mais menus e tem permissão para consultar qualquer ordem).

Links para acesso ao sistema:

PreHom: https://prehom.dpf.gov.br/mobilizacao2/inicio

Homologação: https://sistemashom.dpf.gov.br/mobilizacao2/missao-policial/consultar






In [77]:
type(FileContent)

str

In [79]:
file1.close()

In [80]:
with open(example1, "r") as arquivo:
    dados = arquivo.read()
    print(dados)

https://prehom.dpf.gov.br/siscaer

https://prehom.dpf.gov.br/siscaer-internet

https://prehom.dpf.gov.br/siscaer-publico-web/#/

mob2

Hierarquia São Paulo:


Cadastrar com: heron.hwpb (Usuário comum)

Aprovar pela AD com: estevao.egl (Autoridade Determinante)

Aprovar pela AS com: rosseti.dr (Autoridade Superior)

Aprovar pelo DG com: galloro.ravg (Diretor Geral)

NEIVA MARQUES SOCHETE VIVAN neiva.nmsv
rodrigo souza de oliveira rodrigo souza.rso

Usuário Semob: souza.rso (Esse usuário equivale ao perfil ADM, visualiza mais menus e tem permissão para consultar qualquer ordem).

Links para acesso ao sistema:

PreHom: https://prehom.dpf.gov.br/mobilizacao2/inicio

Homologação: https://sistemashom.dpf.gov.br/mobilizacao2/missao-policial/consultar






In [81]:
arquivo.close()

In [82]:
print(dados)

https://prehom.dpf.gov.br/siscaer

https://prehom.dpf.gov.br/siscaer-internet

https://prehom.dpf.gov.br/siscaer-publico-web/#/

mob2

Hierarquia São Paulo:


Cadastrar com: heron.hwpb (Usuário comum)

Aprovar pela AD com: estevao.egl (Autoridade Determinante)

Aprovar pela AS com: rosseti.dr (Autoridade Superior)

Aprovar pelo DG com: galloro.ravg (Diretor Geral)

NEIVA MARQUES SOCHETE VIVAN neiva.nmsv
rodrigo souza de oliveira rodrigo souza.rso

Usuário Semob: souza.rso (Esse usuário equivale ao perfil ADM, visualiza mais menus e tem permissão para consultar qualquer ordem).

Links para acesso ao sistema:

PreHom: https://prehom.dpf.gov.br/mobilizacao2/inicio

Homologação: https://sistemashom.dpf.gov.br/mobilizacao2/missao-policial/consultar






In [86]:
with open(example1, "r") as info:
    print(info.read(10))

https://pr


In [111]:
file = 'criando.txt'
with open(file, "w") as escrever:
    escrever.write('Bom dia!!')


In [112]:
with open(file, "r") as lendo:
    print(lendo.read())

Bom dia!!


In [119]:
with open(file, "w") as escrever:
    escrever.write('Tamo Junto!!\n')

In [120]:
with open(file, "r") as lendo:
    print(lendo.read())

Tamo Junto!!



In [121]:
with open(file, 'a') as escrever:
    escrever.write("É nois!!")

In [122]:
with open(file, "r") as lendo:
    print(lendo.read())

Tamo Junto!!
É nois!!


In [124]:
import pandas as pd
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})
df['a']==1

0     True
1    False
2     True
Name: a, dtype: bool

In [125]:
import numpy as np

In [130]:
a = np.array([5, 6, 10, 2])
a

array([ 5,  6, 10,  2])

In [131]:
type(a)

numpy.ndarray

In [132]:
a.dtype

dtype('int32')

In [133]:
a.size

4

In [134]:
a.ndim

1

In [136]:
a.shape

(4,)

In [137]:
b =np.array([1.5, 5.6, 8.9, 1.3])
b

array([1.5, 5.6, 8.9, 1.3])

In [138]:
type(b)

numpy.ndarray

In [140]:
b.dtype

dtype('float64')

In [144]:
c = np.array([0, 10, 20, 50])

In [145]:
c [0] = 100

In [147]:
c[3] = 0

In [148]:
c[1:3]

array([10, 20])

In [150]:
c[1:3] = 300, 400
c

array([100, 300, 400,   0])

In [155]:
u = [1, 0]
v = [0, 1]
z = []

for n, m in zip(u,v):
    z.append(n + m)
z

[1, 1]

In [156]:
u = [1, 0]
v = [0, 1]
z = []

for n, m in zip(u,v):
    z.append(n - m)
z

[1, -1]

In [160]:
y = np.array([1,2])
z = []
for m in y:
    z.append(2 * m)
z

[2, 4]

In [163]:
u = np.array([1,2])
v = np.array([3,2])
z = []

for n, m in zip(u,v):
    z.append(n*m)
z

[3, 4]

In [165]:
u = np.array([1,2])
v = np.array([3,2])
result = np.dot(u,v)
result

7

In [166]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [170]:
a = np.array([1,1])
b = np.array([1,-1])
c = []
for i, j in zip(a, b):
    c.append(i*j)
c


[1, -1]

In [171]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [172]:
# Import the libraries

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

In [174]:
 #Plotting functions

def Plotvec1(u, z, v):
    
    ax = plt.axes()
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)
    plt.text(*(u + 0.1), 'u')
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)
    plt.text(*(v + 0.1), 'v')
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

In [175]:
a = ["0", 1, "two", "3", 4]
a

['0', 1, 'two', '3', 4]

In [176]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [177]:

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [178]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [184]:
select = [0, 2, 3]
c = []

In [194]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])

a.ndim
a.size

5

In [190]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])

B=np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [197]:
a=np.array([0,1,0,1,0])

b = np.array ([1,0,1,0,1])

a * b

array([0, 0, 0, 0, 0])

In [198]:
a=np.array([0,1])

b = np.array ([1,0])

np.dot (a, b)

0

In [199]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [200]:
a=np.array([1,1,1,1,1])
b =[]
for i in a:
    b.append(i+10)
b

[11, 11, 11, 11, 11]

In [201]:
a = int (3.2)
a

3

In [202]:
A = '1234567'
A [1 :: 2]


'246'

In [203]:
Name = "Michael Jackson"
Name.find ('el')

5

In [204]:
A = ((11,12), [21,22])
A [1]

[21, 22]

In [205]:
'1,2,3,4'.split (', ')

['1,2,3,4']

In [206]:
A = [1, 'a']
B = [2,1, 'd']
A+B

[1, 'a', 2, 1, 'd']

In [210]:
V = {'A', 'B'}
V.add('C')
V

{'A', 'B', 'C'}

In [211]:
V = {'A', 'B', 'C'}


In [212]:
V.add ('C')
V

{'A', 'B', 'C'}

In [216]:
for n in range(3):
    print(n + 1)

1
2
3


In [218]:
A=['1','2','3']

for i in A:
    print(2*i)

11
22
33


In [223]:
def Adicionar(x, y):
    z = y + x
    return (y)

In [224]:
Adicionar('1', '1')

'1'